# Generated by Django 6.0.4 on 2026-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sreality_id', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('area_m2', models.IntegerField()),
                ('district', models.IntegerField()),
                ('distance_to_local_hub', models.FloatField()),
                ('furnished', models.BooleanField(default=False)),
                ('partly_furnished', models.BooleanField(default=False)),
                ('not_furnished', models.BooleanField(default=False)),
                ('metro', models.BooleanField(default=False)),
                ('tram', models.BooleanField(default=False)),
                ('new_building', models.BooleanField(default=False)),
                ('after_reconstruction', models.BooleanField(default=False)),
                ('brick', models.BooleanField(default=False)),
                ('panel', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('cellar', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('parking_lots', models.BooleanField(default=False)),
                ('predicted_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
